package com.baby.dbdownloader;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOVIE_OBJECT.
 */
public class MovieObject {

    private Long id;
    /** Not-null value. */
    private String MovieId;
    /** Not-null value. */
    private String MovieTitle;
    private String Poster;
    private String URLLink;
    private String Path;
    private String Downloaded;
    private String Status;

    public MovieObject() {
    }

    public MovieObject(Long id) {
        this.id = id;
    }

    public MovieObject(Long id, String MovieId, String MovieTitle, String Poster, String URLLink, String Path, String Downloaded, String Status) {
        this.id = id;
        this.MovieId = MovieId;
        this.MovieTitle = MovieTitle;
        this.Poster = Poster;
        this.URLLink = URLLink;
        this.Path = Path;
        this.Downloaded = Downloaded;
        this.Status = Status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMovieId() {
        return MovieId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMovieId(String MovieId) {
        this.MovieId = MovieId;
    }

    /** Not-null value. */
    public String getMovieTitle() {
        return MovieTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMovieTitle(String MovieTitle) {
        this.MovieTitle = MovieTitle;
    }

    public String getPoster() {
        return Poster;
    }

    public void setPoster(String Poster) {
        this.Poster = Poster;
    }

    public String getURLLink() {
        return URLLink;
    }

    public void setURLLink(String URLLink) {
        this.URLLink = URLLink;
    }

    public String getPath() {
        return Path;
    }

    public void setPath(String Path) {
        this.Path = Path;
    }

    public String getDownloaded() {
        return Downloaded;
    }

    public void setDownloaded(String Downloaded) {
        this.Downloaded = Downloaded;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

}
